// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbvH9KdFj3MWEGTZad23SYtzrJNNMGF7g',
    appId: '1:171993035466:web:67ce2e6c0e0d113d603a33',
    messagingSenderId: '171993035466',
    projectId: 'app-lista-tarefas-fatec',
    authDomain: 'app-lista-tarefas-fatec.firebaseapp.com',
    storageBucket: 'app-lista-tarefas-fatec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX8uUnmGdQQBbJQx_QcDBG_XmcCkQV5JI',
    appId: '1:171993035466:android:3d32f2fffc29e1b0603a33',
    messagingSenderId: '171993035466',
    projectId: 'app-lista-tarefas-fatec',
    storageBucket: 'app-lista-tarefas-fatec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbyxNTgQInthTIkMsm3yGdco5iYMVHeyU',
    appId: '1:171993035466:ios:5910be8afa0f7841603a33',
    messagingSenderId: '171993035466',
    projectId: 'app-lista-tarefas-fatec',
    storageBucket: 'app-lista-tarefas-fatec.appspot.com',
    iosBundleId: 'com.example.appListaComprasFirebase',
  );
}
